const product = {
  Products: [
    {
      id: 1,
      name: "Fresh Tomato (Tamatar)",
      image: "/images/tomato.jpg",
      currentPrice: 50,
      prevPrice: 60,
      unit: "1 Kg",
      offer: 17,
      quantity: 1,
      category: "vegetable",
    },
    {
      id: 2,
      name: "Potato Old (Aaloo)",
      image: "/images/potato.jpg",
      currentPrice: 20,
      prevPrice: 30,
      unit: "1 Kg",
      offer: 3,
      quantity: 1,
      category: "vegetable", 
    },
    {
      id: 3,
      name: "Onion (Pyaaz)",
      image: "/images/onion.jpg",
      currentPrice: 30,
      prevPrice: 50,
      unit: "1 Kg",
      offer: 40,
      quantity: 1,
      category: "vegetable",
    },
    {
      id: 4,
      name: "Garlic (Lehsun)",
      image: "/images/garlic.jpg",
      currentPrice: 40,
      prevPrice: 60,
      unit: "500 gm",
      offer: 33,
      quantity: 1,
      category: "vegetable",
    },
    {
      id: 5,
      name: "Brinjal (Baigan)",
      image: "/images/brinjal.jpg",
      currentPrice: 20,
      prevPrice: 35,
      unit: "500 gm",
      offer: 20,
      quantity: 1,
      category: "vegetable",
    },
    {
      id: 6,
      name: "Green Capsicum (Shimla Mirch)",
      image: "/images/capsicum.jpg",
      currentPrice: 20,
      prevPrice: 40,
      unit: "250 gm",
      offer: 20,
      quantity: 1,
      category: "vegetable",
    },
    {
      id: 7,
      name: "Elephant Foot Yam (Sooran)",
      image: "/images/Foot-Yam.webp",
      currentPrice: 50,
      prevPrice: 60,
      unit: "1 Kg",
      offer: 17,
      quantity: 1,
      category: "vegetable",
    },
    {
      id: 8,
      name: "Green Chilli (hari Mirch)",
      image: "/images/chilli.jpg",
      currentPrice: 15,
      prevPrice: 20,
      unit: "250 gm",
      offer: 15,
      quantity: 1,
      category: "vegetable",
    },
    {
      id: 9,
      name: "kashmiri Apple (Seb)",
      image: "/images/apple.jpg",
      currentPrice: 165,
      prevPrice: 180,
      unit: "1 kg",
      offer: 3,
      quantity: 1,
      category: "fruit",
    },
    {
      id: 10,
      name: "Papaya (Papita)",
      image: "/images/papaya.jpg",
      currentPrice: 55,
      prevPrice: 60,
      unit: "1 Unit",
      offer: 8,
      quantity: 1,
      category: "fruit",
    },
    {
      id: 11,
      name: "Banana (Kela)",
      image: "/images/banana.png",
      currentPrice: 40,
      prevPrice: 60,
      unit: "1 Dozen",
      offer: 8,
      quantity: 1,
      category: "fruit",
    },
    {
      id: 12,
      name: "Kiwi",
      image: "/images/kiwi.jpg",
      currentPrice: 20,
      prevPrice: 40,
      unit: "1 Unit",
      offer: 8,
      quantity: 1,
      category: "fruit",
    },
    {
      id: 13,
      name: "Pineapple",
      image: "/images/pineapple.png",
      currentPrice: 90,
      prevPrice: 110,
      unit: "1 Unit",
      offer: 8,
      quantity: 1,
      category: "fruit",
    },
    {
      id: 14,
      name: "Almond (Badam)",
      image: "/images/almond.jpg",
      currentPrice: 225,
      prevPrice: 300,
      unit: "500 gm",
      offer: 15,
      quantity: 1,
      category: "dry",
    },
    {
      id: 15,
      name: "Dates Premium (Khajur)",
      image: "/images/dates.jpg",
      currentPrice: 180,
      prevPrice: 230,
      unit: "500 gm",
      offer: 10,
      quantity: 1,
      category: "dry",
    },
    {
      id: 16,
      name: "Fresh Meat",
      image: "/images/meat.jpg",
      currentPrice: 400,
      prevPrice: 450,
      unit: "500 gm",
      offer: 10,
      quantity: 1,
      category: "nonveg",
    },
  ],
};
export default product;
